apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: production
data:
  catalog-service-url: "catalog-service.production.svc.cluster.local:50051"
  user-service-url: "user-service.production.svc.cluster.local:50052"
  payment-service-url: "payment-service.production.svc.cluster.local:50055"
  inventory-service-url: "inventory-service.production.svc.cluster.local:50056"
