apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: bookstore-dev
data:
  HTTP_PORT: "8084"
  ENV: "development"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "bookstore"
  DB_NAME: "catalog_db"
  DB_SSLMODE: "disable"
  DEFAULT_PAGE_SIZE: "20"
  MAX_PAGE_SIZE: "100"
  LOG_LEVEL: "debug"
