apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: bookstore-dev
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  selector:
    app: catalog-service
