/* eslint-disable */

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as WishlistImport } from "./routes/wishlist";
import { Route as RegisterImport } from "./routes/register";
import { Route as LoginImport } from "./routes/login";
import { Route as GenresImport } from "./routes/genres";
import { Route as BooksImport } from "./routes/books";
import { Route as IndexImport } from "./routes/index";
import { Route as GenresSlugImport } from "./routes/genres.$slug";
import { Route as BooksIdImport } from "./routes/books.$id";
import { Route as AuthorsIdImport } from "./routes/authors.$id";
import { Route as AdminBooksImport } from "./routes/admin.books";

// Create/Update Routes

const WishlistRoute = WishlistImport.update({
  id: "/wishlist",
  path: "/wishlist",
  getParentRoute: () => rootRoute,
} as any);

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const GenresRoute = GenresImport.update({
  id: "/genres",
  path: "/genres",
  getParentRoute: () => rootRoute,
} as any);

const BooksRoute = BooksImport.update({
  id: "/books",
  path: "/books",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const GenresSlugRoute = GenresSlugImport.update({
  id: "/genres/$slug",
  path: "/genres/$slug",
  getParentRoute: () => rootRoute,
} as any);

const BooksIdRoute = BooksIdImport.update({
  id: "/books/$id",
  path: "/books/$id",
  getParentRoute: () => rootRoute,
} as any);

const AuthorsIdRoute = AuthorsIdImport.update({
  id: "/authors/$id",
  path: "/authors/$id",
  getParentRoute: () => rootRoute,
} as any);

const AdminBooksRoute = AdminBooksImport.update({
  id: "/admin/books",
  path: "/admin/books",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/books": {
      id: "/books";
      path: "/books";
      fullPath: "/books";
      preLoaderRoute: typeof BooksImport;
      parentRoute: typeof rootRoute;
    };
    "/genres": {
      id: "/genres";
      path: "/genres";
      fullPath: "/genres";
      preLoaderRoute: typeof GenresImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    "/wishlist": {
      id: "/wishlist";
      path: "/wishlist";
      fullPath: "/wishlist";
      preLoaderRoute: typeof WishlistImport;
      parentRoute: typeof rootRoute;
    };
    "/admin/books": {
      id: "/admin/books";
      path: "/admin/books";
      fullPath: "/admin/books";
      preLoaderRoute: typeof AdminBooksImport;
      parentRoute: typeof rootRoute;
    };
    "/authors/$id": {
      id: "/authors/$id";
      path: "/authors/$id";
      fullPath: "/authors/$id";
      preLoaderRoute: typeof AuthorsIdImport;
      parentRoute: typeof rootRoute;
    };
    "/books/$id": {
      id: "/books/$id";
      path: "/books/$id";
      fullPath: "/books/$id";
      preLoaderRoute: typeof BooksIdImport;
      parentRoute: typeof rootRoute;
    };
    "/genres/$slug": {
      id: "/genres/$slug";
      path: "/genres/$slug";
      fullPath: "/genres/$slug";
      preLoaderRoute: typeof GenresSlugImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/books": typeof BooksRoute;
  "/genres": typeof GenresRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/wishlist": typeof WishlistRoute;
  "/admin/books": typeof AdminBooksRoute;
  "/authors/$id": typeof AuthorsIdRoute;
  "/books/$id": typeof BooksIdRoute;
  "/genres/$slug": typeof GenresSlugRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/books": typeof BooksRoute;
  "/genres": typeof GenresRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/wishlist": typeof WishlistRoute;
  "/admin/books": typeof AdminBooksRoute;
  "/authors/$id": typeof AuthorsIdRoute;
  "/books/$id": typeof BooksIdRoute;
  "/genres/$slug": typeof GenresSlugRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/books": typeof BooksRoute;
  "/genres": typeof GenresRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/wishlist": typeof WishlistRoute;
  "/admin/books": typeof AdminBooksRoute;
  "/authors/$id": typeof AuthorsIdRoute;
  "/books/$id": typeof BooksIdRoute;
  "/genres/$slug": typeof GenresSlugRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/books"
    | "/genres"
    | "/login"
    | "/register"
    | "/wishlist"
    | "/admin/books"
    | "/authors/$id"
    | "/books/$id"
    | "/genres/$slug";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/books"
    | "/genres"
    | "/login"
    | "/register"
    | "/wishlist"
    | "/admin/books"
    | "/authors/$id"
    | "/books/$id"
    | "/genres/$slug";
  id:
    | "__root__"
    | "/"
    | "/books"
    | "/genres"
    | "/login"
    | "/register"
    | "/wishlist"
    | "/admin/books"
    | "/authors/$id"
    | "/books/$id"
    | "/genres/$slug";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BooksRoute: typeof BooksRoute;
  GenresRoute: typeof GenresRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  WishlistRoute: typeof WishlistRoute;
  AdminBooksRoute: typeof AdminBooksRoute;
  AuthorsIdRoute: typeof AuthorsIdRoute;
  BooksIdRoute: typeof BooksIdRoute;
  GenresSlugRoute: typeof GenresSlugRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  GenresRoute: GenresRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WishlistRoute: WishlistRoute,
  AdminBooksRoute: AdminBooksRoute,
  AuthorsIdRoute: AuthorsIdRoute,
  BooksIdRoute: BooksIdRoute,
  GenresSlugRoute: GenresSlugRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/books",
        "/genres",
        "/login",
        "/register",
        "/wishlist",
        "/admin/books",
        "/authors/$id",
        "/books/$id",
        "/genres/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/books": {
      "filePath": "books.tsx"
    },
    "/genres": {
      "filePath": "genres.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/wishlist": {
      "filePath": "wishlist.tsx"
    },
    "/admin/books": {
      "filePath": "admin.books.tsx"
    },
    "/authors/$id": {
      "filePath": "authors.$id.tsx"
    },
    "/books/$id": {
      "filePath": "books.$id.tsx"
    },
    "/genres/$slug": {
      "filePath": "genres.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
