/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WishlistRouteImport } from "./routes/wishlist";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as PublishersRouteImport } from "./routes/publishers";
import { Route as OrdersRouteImport } from "./routes/orders";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as GenresRouteImport } from "./routes/genres";
import { Route as CheckoutRouteImport } from "./routes/checkout";
import { Route as CartRouteImport } from "./routes/cart";
import { Route as BooksRouteImport } from "./routes/books";
import { Route as AuthorsRouteImport } from "./routes/authors";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PublishersIdRouteImport } from "./routes/publishers.$id";
import { Route as OrdersOrderIdRouteImport } from "./routes/orders.$orderId";
import { Route as GenresSlugRouteImport } from "./routes/genres.$slug";
import { Route as BooksIdRouteImport } from "./routes/books.$id";
import { Route as AuthorsIdRouteImport } from "./routes/authors.$id";
import { Route as AdminDashboardRouteImport } from "./routes/admin.dashboard";
import { Route as AdminBooksRouteImport } from "./routes/admin.books";

const WishlistRoute = WishlistRouteImport.update({
  id: "/wishlist",
  path: "/wishlist",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const PublishersRoute = PublishersRouteImport.update({
  id: "/publishers",
  path: "/publishers",
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersRoute = OrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const GenresRoute = GenresRouteImport.update({
  id: "/genres",
  path: "/genres",
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutRoute = CheckoutRouteImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => rootRouteImport,
} as any);
const CartRoute = CartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => rootRouteImport,
} as any);
const BooksRoute = BooksRouteImport.update({
  id: "/books",
  path: "/books",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthorsRoute = AuthorsRouteImport.update({
  id: "/authors",
  path: "/authors",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PublishersIdRoute = PublishersIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => PublishersRoute,
} as any);
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: "/$orderId",
  path: "/$orderId",
  getParentRoute: () => OrdersRoute,
} as any);
const GenresSlugRoute = GenresSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => GenresRoute,
} as any);
const BooksIdRoute = BooksIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => BooksRoute,
} as any);
const AuthorsIdRoute = AuthorsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => AuthorsRoute,
} as any);
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: "/admin/dashboard",
  path: "/admin/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: "/admin/books",
  path: "/admin/books",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/authors": typeof AuthorsRouteWithChildren;
  "/books": typeof BooksRouteWithChildren;
  "/cart": typeof CartRoute;
  "/checkout": typeof CheckoutRoute;
  "/genres": typeof GenresRouteWithChildren;
  "/login": typeof LoginRoute;
  "/orders": typeof OrdersRouteWithChildren;
  "/publishers": typeof PublishersRouteWithChildren;
  "/register": typeof RegisterRoute;
  "/wishlist": typeof WishlistRoute;
  "/admin/books": typeof AdminBooksRoute;
  "/admin/dashboard": typeof AdminDashboardRoute;
  "/authors/$id": typeof AuthorsIdRoute;
  "/books/$id": typeof BooksIdRoute;
  "/genres/$slug": typeof GenresSlugRoute;
  "/orders/$orderId": typeof OrdersOrderIdRoute;
  "/publishers/$id": typeof PublishersIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/authors": typeof AuthorsRouteWithChildren;
  "/books": typeof BooksRouteWithChildren;
  "/cart": typeof CartRoute;
  "/checkout": typeof CheckoutRoute;
  "/genres": typeof GenresRouteWithChildren;
  "/login": typeof LoginRoute;
  "/orders": typeof OrdersRouteWithChildren;
  "/publishers": typeof PublishersRouteWithChildren;
  "/register": typeof RegisterRoute;
  "/wishlist": typeof WishlistRoute;
  "/admin/books": typeof AdminBooksRoute;
  "/admin/dashboard": typeof AdminDashboardRoute;
  "/authors/$id": typeof AuthorsIdRoute;
  "/books/$id": typeof BooksIdRoute;
  "/genres/$slug": typeof GenresSlugRoute;
  "/orders/$orderId": typeof OrdersOrderIdRoute;
  "/publishers/$id": typeof PublishersIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/authors": typeof AuthorsRouteWithChildren;
  "/books": typeof BooksRouteWithChildren;
  "/cart": typeof CartRoute;
  "/checkout": typeof CheckoutRoute;
  "/genres": typeof GenresRouteWithChildren;
  "/login": typeof LoginRoute;
  "/orders": typeof OrdersRouteWithChildren;
  "/publishers": typeof PublishersRouteWithChildren;
  "/register": typeof RegisterRoute;
  "/wishlist": typeof WishlistRoute;
  "/admin/books": typeof AdminBooksRoute;
  "/admin/dashboard": typeof AdminDashboardRoute;
  "/authors/$id": typeof AuthorsIdRoute;
  "/books/$id": typeof BooksIdRoute;
  "/genres/$slug": typeof GenresSlugRoute;
  "/orders/$orderId": typeof OrdersOrderIdRoute;
  "/publishers/$id": typeof PublishersIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/authors"
    | "/books"
    | "/cart"
    | "/checkout"
    | "/genres"
    | "/login"
    | "/orders"
    | "/publishers"
    | "/register"
    | "/wishlist"
    | "/admin/books"
    | "/admin/dashboard"
    | "/authors/$id"
    | "/books/$id"
    | "/genres/$slug"
    | "/orders/$orderId"
    | "/publishers/$id";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/authors"
    | "/books"
    | "/cart"
    | "/checkout"
    | "/genres"
    | "/login"
    | "/orders"
    | "/publishers"
    | "/register"
    | "/wishlist"
    | "/admin/books"
    | "/admin/dashboard"
    | "/authors/$id"
    | "/books/$id"
    | "/genres/$slug"
    | "/orders/$orderId"
    | "/publishers/$id";
  id:
    | "__root__"
    | "/"
    | "/authors"
    | "/books"
    | "/cart"
    | "/checkout"
    | "/genres"
    | "/login"
    | "/orders"
    | "/publishers"
    | "/register"
    | "/wishlist"
    | "/admin/books"
    | "/admin/dashboard"
    | "/authors/$id"
    | "/books/$id"
    | "/genres/$slug"
    | "/orders/$orderId"
    | "/publishers/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthorsRoute: typeof AuthorsRouteWithChildren;
  BooksRoute: typeof BooksRouteWithChildren;
  CartRoute: typeof CartRoute;
  CheckoutRoute: typeof CheckoutRoute;
  GenresRoute: typeof GenresRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  OrdersRoute: typeof OrdersRouteWithChildren;
  PublishersRoute: typeof PublishersRouteWithChildren;
  RegisterRoute: typeof RegisterRoute;
  WishlistRoute: typeof WishlistRoute;
  AdminBooksRoute: typeof AdminBooksRoute;
  AdminDashboardRoute: typeof AdminDashboardRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/wishlist": {
      id: "/wishlist";
      path: "/wishlist";
      fullPath: "/wishlist";
      preLoaderRoute: typeof WishlistRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/publishers": {
      id: "/publishers";
      path: "/publishers";
      fullPath: "/publishers";
      preLoaderRoute: typeof PublishersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/orders": {
      id: "/orders";
      path: "/orders";
      fullPath: "/orders";
      preLoaderRoute: typeof OrdersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/genres": {
      id: "/genres";
      path: "/genres";
      fullPath: "/genres";
      preLoaderRoute: typeof GenresRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/checkout": {
      id: "/checkout";
      path: "/checkout";
      fullPath: "/checkout";
      preLoaderRoute: typeof CheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cart": {
      id: "/cart";
      path: "/cart";
      fullPath: "/cart";
      preLoaderRoute: typeof CartRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/books": {
      id: "/books";
      path: "/books";
      fullPath: "/books";
      preLoaderRoute: typeof BooksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/authors": {
      id: "/authors";
      path: "/authors";
      fullPath: "/authors";
      preLoaderRoute: typeof AuthorsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/publishers/$id": {
      id: "/publishers/$id";
      path: "/$id";
      fullPath: "/publishers/$id";
      preLoaderRoute: typeof PublishersIdRouteImport;
      parentRoute: typeof PublishersRoute;
    };
    "/orders/$orderId": {
      id: "/orders/$orderId";
      path: "/$orderId";
      fullPath: "/orders/$orderId";
      preLoaderRoute: typeof OrdersOrderIdRouteImport;
      parentRoute: typeof OrdersRoute;
    };
    "/genres/$slug": {
      id: "/genres/$slug";
      path: "/$slug";
      fullPath: "/genres/$slug";
      preLoaderRoute: typeof GenresSlugRouteImport;
      parentRoute: typeof GenresRoute;
    };
    "/books/$id": {
      id: "/books/$id";
      path: "/$id";
      fullPath: "/books/$id";
      preLoaderRoute: typeof BooksIdRouteImport;
      parentRoute: typeof BooksRoute;
    };
    "/authors/$id": {
      id: "/authors/$id";
      path: "/$id";
      fullPath: "/authors/$id";
      preLoaderRoute: typeof AuthorsIdRouteImport;
      parentRoute: typeof AuthorsRoute;
    };
    "/admin/dashboard": {
      id: "/admin/dashboard";
      path: "/admin/dashboard";
      fullPath: "/admin/dashboard";
      preLoaderRoute: typeof AdminDashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/books": {
      id: "/admin/books";
      path: "/admin/books";
      fullPath: "/admin/books";
      preLoaderRoute: typeof AdminBooksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthorsRouteChildren {
  AuthorsIdRoute: typeof AuthorsIdRoute;
}

const AuthorsRouteChildren: AuthorsRouteChildren = {
  AuthorsIdRoute: AuthorsIdRoute,
};

const AuthorsRouteWithChildren =
  AuthorsRoute._addFileChildren(AuthorsRouteChildren);

interface BooksRouteChildren {
  BooksIdRoute: typeof BooksIdRoute;
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksIdRoute: BooksIdRoute,
};

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren);

interface GenresRouteChildren {
  GenresSlugRoute: typeof GenresSlugRoute;
}

const GenresRouteChildren: GenresRouteChildren = {
  GenresSlugRoute: GenresSlugRoute,
};

const GenresRouteWithChildren =
  GenresRoute._addFileChildren(GenresRouteChildren);

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute;
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
};

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren);

interface PublishersRouteChildren {
  PublishersIdRoute: typeof PublishersIdRoute;
}

const PublishersRouteChildren: PublishersRouteChildren = {
  PublishersIdRoute: PublishersIdRoute,
};

const PublishersRouteWithChildren = PublishersRoute._addFileChildren(
  PublishersRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRouteWithChildren,
  BooksRoute: BooksRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  GenresRoute: GenresRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PublishersRoute: PublishersRouteWithChildren,
  RegisterRoute: RegisterRoute,
  WishlistRoute: WishlistRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminDashboardRoute: AdminDashboardRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
