apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: bookstore-dev
data:
  HTTP_PORT: "8089"
  ENV: "development"
  SERVICE_NAME: "notification-service"
  LOG_LEVEL: "info"
  SHUTDOWN_TIMEOUT: "10s"
  RABBITMQ_URL: "amqp://bookstore:dev_password@rabbitmq:5672/"
  RABBITMQ_EXCHANGE: "bookstore.events"
  RABBITMQ_QUEUE: "notification-service"
  RABBITMQ_ROUTING_KEYS: "user.*,wishlist.*,cart.*,order.*"
  RABBITMQ_PREFETCH_COUNT: "10"
