package seeds

import "github.com/google/uuid"

// BookSeed represents a book with associated metadata and relationship keys.
type BookSeed struct {
	ID              uuid.UUID
	ISBN            string
	Title           string
	Description     string
	Price           float64
	Stock           int
	PublisherCode   string
	CoverImageURL   string
	PublicationDate string
	Language        string
	PageCount       int
	CategorySlugs   []string
	AuthorCodes     []string
}

var bookSeeds = []BookSeed{
	{
		ID:              UUIDFromString("book:9780316229296"),
		ISBN:            "9780316229296",
		Title:           "The Fifth Season",
		Description:     "A dying world, fractured society, and a hidden power intertwine in the first book of the Broken Earth trilogy.",
		Price:           18.99,
		Stock:           120,
		PublisherCode:   "tor-books",
		CoverImageURL:   "",
		PublicationDate: "2015-08-04",
		Language:        "English",
		PageCount:       512,
		CategorySlugs:   []string{"science-fiction", "fantasy"},
		AuthorCodes:     []string{"nk-jemisin"},
	},
	{
		ID:              UUIDFromString("book:9780316229265"),
		ISBN:            "9780316229265",
		Title:           "The Obelisk Gate",
		Description:     "The second installment of the Broken Earth trilogy raises the stakes as the Stillness hurtles toward collapse.",
		Price:           18.99,
		Stock:           110,
		PublisherCode:   "tor-books",
		CoverImageURL:   "",
		PublicationDate: "2016-08-16",
		Language:        "English",
		PageCount:       448,
		CategorySlugs:   []string{"science-fiction", "fantasy"},
		AuthorCodes:     []string{"nk-jemisin"},
	},
	{
		ID:              UUIDFromString("book:9780316229241"),
		ISBN:            "9780316229241",
		Title:           "The Stone Sky",
		Description:     "The Hugo Award-winning finale delivers a powerful conclusion to Essun and Nassun's story.",
		Price:           18.99,
		Stock:           105,
		PublisherCode:   "tor-books",
		CoverImageURL:   "",
		PublicationDate: "2017-08-15",
		Language:        "English",
		PageCount:       464,
		CategorySlugs:   []string{"science-fiction", "fantasy"},
		AuthorCodes:     []string{"nk-jemisin"},
	},
	{
		ID:              UUIDFromString("book:9780765311788"),
		ISBN:            "9780765311788",
		Title:           "Mistborn: The Final Empire",
		Description:     "A daring crew attempts to overthrow the immortal Lord Ruler using allomantic magic.",
		Price:           16.99,
		Stock:           140,
		PublisherCode:   "tor-books",
		CoverImageURL:   "",
		PublicationDate: "2006-07-25",
		Language:        "English",
		PageCount:       672,
		CategorySlugs:   []string{"fantasy"},
		AuthorCodes:     []string{"brandon-sanderson"},
	},
	{
		ID:              UUIDFromString("book:9780765316885"),
		ISBN:            "9780765316885",
		Title:           "Mistborn: The Well of Ascension",
		Description:     "Political intrigue and ancient secrets test Vin and Elend after the uprising succeeds.",
		Price:           17.99,
		Stock:           135,
		PublisherCode:   "tor-books",
		CoverImageURL:   "",
		PublicationDate: "2007-08-21",
		Language:        "English",
		PageCount:       816,
		CategorySlugs:   []string{"fantasy"},
		AuthorCodes:     []string{"brandon-sanderson"},
	},
	{
		ID:              UUIDFromString("book:9780765326362"),
		ISBN:            "9780765326362",
		Title:           "Words of Radiance",
		Description:     "The Stormlight Archive continues with high fantasy warfare, politics, and ancient oaths.",
		Price:           24.99,
		Stock:           95,
		PublisherCode:   "tor-books",
		CoverImageURL:   "",
		PublicationDate: "2014-03-04",
		Language:        "English",
		PageCount:       1088,
		CategorySlugs:   []string{"fantasy"},
		AuthorCodes:     []string{"brandon-sanderson"},
	},
	{
		ID:              UUIDFromString("book:9780765326355"),
		ISBN:            "9780765326355",
		Title:           "The Way of Kings",
		Description:     "The Stormlight Archive opens with legendary battles, shattered oaths, and mysterious storms.",
		Price:           22.99,
		Stock:           100,
		PublisherCode:   "tor-books",
		CoverImageURL:   "",
		PublicationDate: "2010-08-31",
		Language:        "English",
		PageCount:       1008,
		CategorySlugs:   []string{"fantasy"},
		AuthorCodes:     []string{"brandon-sanderson"},
	},
	{
		ID:              UUIDFromString("book:9780441478125"),
		ISBN:            "9780441478125",
		Title:           "The Left Hand of Darkness",
		Description:     "A human envoy must bridge cultural divides on a distant, gender-fluid world.",
		Price:           15.99,
		Stock:           80,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "1969-03-01",
		Language:        "English",
		PageCount:       304,
		CategorySlugs:   []string{"science-fiction"},
		AuthorCodes:     []string{"ursula-k-le-guin"},
	},
	{
		ID:              UUIDFromString("book:9780060512750"),
		ISBN:            "9780060512750",
		Title:           "The Dispossessed",
		Description:     "Paired worlds examine anarchism, capitalism, and the search for freedom.",
		Price:           16.99,
		Stock:           76,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "1974-05-01",
		Language:        "English",
		PageCount:       400,
		CategorySlugs:   []string{"science-fiction", "philosophy"},
		AuthorCodes:     []string{"ursula-k-le-guin"},
	},
	{
		ID:              UUIDFromString("book:9780316129084"),
		ISBN:            "9780316129084",
		Title:           "Leviathan Wakes",
		Description:     "Humanity's expansion into the solar system erupts into conspiracy and war.",
		Price:           18.99,
		Stock:           120,
		PublisherCode:   "orbit-books",
		CoverImageURL:   "",
		PublicationDate: "2011-06-15",
		Language:        "English",
		PageCount:       592,
		CategorySlugs:   []string{"science-fiction", "thriller"},
		AuthorCodes:     []string{"james-sa-corey"},
	},
	{
		ID:              UUIDFromString("book:9780316129060"),
		ISBN:            "9780316129060",
		Title:           "Caliban's War",
		Description:     "The crew of the Rocinante is dragged back into conflict as tensions escalate across the system.",
		Price:           18.99,
		Stock:           115,
		PublisherCode:   "orbit-books",
		CoverImageURL:   "",
		PublicationDate: "2012-06-26",
		Language:        "English",
		PageCount:       624,
		CategorySlugs:   []string{"science-fiction", "thriller"},
		AuthorCodes:     []string{"james-sa-corey"},
	},
	{
		ID:              UUIDFromString("book:9780316129077"),
		ISBN:            "9780316129077",
		Title:           "Abaddon's Gate",
		Description:     "A mysterious ring beyond Neptune threatens to reshape human destiny.",
		Price:           18.99,
		Stock:           112,
		PublisherCode:   "orbit-books",
		CoverImageURL:   "",
		PublicationDate: "2013-06-04",
		Language:        "English",
		PageCount:       592,
		CategorySlugs:   []string{"science-fiction", "thriller"},
		AuthorCodes:     []string{"james-sa-corey"},
	},
	{
		ID:              UUIDFromString("book:9780553418026"),
		ISBN:            "9780553418026",
		Title:           "The Martian",
		Description:     "An astronaut must survive alone on Mars with ingenuity and science.",
		Price:           17.99,
		Stock:           150,
		PublisherCode:   "crown",
		CoverImageURL:   "https://m.media-amazon.com/images/I/810W+zAp2DL._SY466_.jpg",
		PublicationDate: "2014-02-11",
		Language:        "English",
		PageCount:       400,
		CategorySlugs:   []string{"science-fiction", "technology"},
		AuthorCodes:     []string{"andy-weir"},
	},
	{
		ID:              UUIDFromString("book:9780593135204"),
		ISBN:            "9780593135204",
		Title:           "Project Hail Mary",
		Description:     "A lone astronaut races to save Earth from an extinction-level threat.",
		Price:           27.99,
		Stock:           98,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "https://m.media-amazon.com/images/I/91ENQs2KLAL._SY466_.jpg",
		PublicationDate: "2021-05-04",
		Language:        "English",
		PageCount:       496,
		CategorySlugs:   []string{"science-fiction", "technology"},
		AuthorCodes:     []string{"andy-weir"},
	},
	{
		ID:              UUIDFromString("book:9780060558123"),
		ISBN:            "9780060558123",
		Title:           "American Gods",
		Description:     "Old gods clash with new in a road trip across mythic America.",
		Price:           17.99,
		Stock:           90,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "https://m.media-amazon.com/images/I/81vOoc2NhoL._SY466_.jpg",
		PublicationDate: "2001-06-19",
		Language:        "English",
		PageCount:       624,
		CategorySlugs:   []string{"fantasy", "mythology"},
		AuthorCodes:     []string{"neil-gaiman"},
	},
	{
		ID:              UUIDFromString("book:9780060853983"),
		ISBN:            "9780060853983",
		Title:           "Good Omens",
		Description:     "An angel and demon team up to avert the apocalypse with humor and heart.",
		Price:           16.99,
		Stock:           88,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "2006-05-23",
		Language:        "English",
		PageCount:       512,
		CategorySlugs:   []string{"fantasy", "young-adult"},
		AuthorCodes:     []string{"neil-gaiman"},
	},
	{
		ID:              UUIDFromString("book:9780061139376"),
		ISBN:            "9780061139376",
		Title:           "Coraline",
		Description:     "A young girl discovers a dark mirror world behind her home's secret door.",
		Price:           10.99,
		Stock:           130,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "2002-08-04",
		Language:        "English",
		PageCount:       176,
		CategorySlugs:   []string{"young-adult", "horror"},
		AuthorCodes:     []string{"neil-gaiman"},
	},
	{
		ID:              UUIDFromString("book:9780385490818"),
		ISBN:            "9780385490818",
		Title:           "The Handmaid's Tale",
		Description:     "A dystopian vision of authoritarian control and resistance.",
		Price:           16.99,
		Stock:           140,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "1986-08-17",
		Language:        "English",
		PageCount:       336,
		CategorySlugs:   []string{"science-fiction", "history"},
		AuthorCodes:     []string{"margaret-atwood"},
	},
	{
		ID:              UUIDFromString("book:9780385721677"),
		ISBN:            "9780385721677",
		Title:           "Oryx and Crake",
		Description:     "A near-future tale examining bioengineering, corporatism, and survival.",
		Price:           15.99,
		Stock:           125,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2003-04-22",
		Language:        "English",
		PageCount:       432,
		CategorySlugs:   []string{"science-fiction", "philosophy"},
		AuthorCodes:     []string{"margaret-atwood"},
	},
	{
		ID:              UUIDFromString("book:9780316556347"),
		ISBN:            "9780316556347",
		Title:           "Circe",
		Description:     "Greek mythology retold through the perspective of the enchantress Circe.",
		Price:           17.99,
		Stock:           118,
		PublisherCode:   "little-brown",
		CoverImageURL:   "",
		PublicationDate: "2018-04-10",
		Language:        "English",
		PageCount:       400,
		CategorySlugs:   []string{"fantasy", "mythology"},
		AuthorCodes:     []string{"madeline-miller"},
	},
	{
		ID:              UUIDFromString("book:9780062060624"),
		ISBN:            "9780062060624",
		Title:           "The Song of Achilles",
		Description:     "A lyrical retelling of the Iliad focusing on Patroclus and Achilles.",
		Price:           16.99,
		Stock:           122,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "2012-08-28",
		Language:        "English",
		PageCount:       416,
		CategorySlugs:   []string{"fantasy", "romance"},
		AuthorCodes:     []string{"madeline-miller"},
	},
	{
		ID:              UUIDFromString("book:9780307743657"),
		ISBN:            "9780307743657",
		Title:           "The Shining",
		Description:     "A family wintering in an isolated hotel spirals into gothic horror.",
		Price:           16.99,
		Stock:           160,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "1977-01-28",
		Language:        "English",
		PageCount:       464,
		CategorySlugs:   []string{"horror", "thriller"},
		AuthorCodes:     []string{"stephen-king"},
	},
	{
		ID:              UUIDFromString("book:9781501142970"),
		ISBN:            "9781501142970",
		Title:           "It",
		Description:     "Childhood friends confront an ancient evil haunting their hometown.",
		Price:           19.99,
		Stock:           155,
		PublisherCode:   "simon-schuster",
		CoverImageURL:   "",
		PublicationDate: "1986-09-15",
		Language:        "English",
		PageCount:       1184,
		CategorySlugs:   []string{"horror"},
		AuthorCodes:     []string{"stephen-king"},
	},
	{
		ID:              UUIDFromString("book:9781451627282"),
		ISBN:            "9781451627282",
		Title:           "11/22/63",
		Description:     "Time travel collides with history in a mission to stop the JFK assassination.",
		Price:           18.99,
		Stock:           130,
		PublisherCode:   "simon-schuster",
		CoverImageURL:   "",
		PublicationDate: "2011-11-08",
		Language:        "English",
		PageCount:       849,
		CategorySlugs:   []string{"thriller", "history"},
		AuthorCodes:     []string{"stephen-king"},
	},
	{
		ID:              UUIDFromString("book:9780525620785"),
		ISBN:            "9780525620785",
		Title:           "Mexican Gothic",
		Description:     "A glamorous socialite investigates sinister secrets in a crumbling mansion.",
		Price:           16.99,
		Stock:           145,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2020-06-30",
		Language:        "English",
		PageCount:       352,
		CategorySlugs:   []string{"horror", "mystery"},
		AuthorCodes:     []string{"silvia-moreno-garcia"},
	},
	{
		ID:              UUIDFromString("book:9780525620761"),
		ISBN:            "9780525620761",
		Title:           "Gods of Jade and Shadow",
		Description:     "A young woman embarks on a mythic quest with the Mayan god of death.",
		Price:           16.99,
		Stock:           120,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2019-07-23",
		Language:        "English",
		PageCount:       352,
		CategorySlugs:   []string{"fantasy", "mythology"},
		AuthorCodes:     []string{"silvia-moreno-garcia"},
	},
	{
		ID:              UUIDFromString("book:9780143113492"),
		ISBN:            "9780143113492",
		Title:           "In the Woods",
		Description:     "A detective unearths childhood trauma while investigating a grisly murder.",
		Price:           15.99,
		Stock:           112,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2007-05-17",
		Language:        "English",
		PageCount:       464,
		CategorySlugs:   []string{"mystery", "thriller"},
		AuthorCodes:     []string{"tana-french"},
	},
	{
		ID:              UUIDFromString("book:9780143115625"),
		ISBN:            "9780143115625",
		Title:           "The Likeness",
		Description:     "An undercover assignment entangles a detective in a close-knit academic circle.",
		Price:           16.99,
		Stock:           108,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2008-07-17",
		Language:        "English",
		PageCount:       528,
		CategorySlugs:   []string{"mystery", "thriller"},
		AuthorCodes:     []string{"tana-french"},
	},
	{
		ID:              UUIDFromString("book:9780062693662"),
		ISBN:            "9780062693662",
		Title:           "Murder on the Orient Express",
		Description:     "Hercule Poirot solves a murder aboard a snowbound luxury train.",
		Price:           12.99,
		Stock:           180,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "1934-01-01",
		Language:        "English",
		PageCount:       288,
		CategorySlugs:   []string{"mystery"},
		AuthorCodes:     []string{"agatha-christie"},
	},
	{
		ID:              UUIDFromString("book:9780062073488"),
		ISBN:            "9780062073488",
		Title:           "And Then There Were None",
		Description:     "Ten strangers on a remote island face a chilling countdown to death.",
		Price:           11.99,
		Stock:           190,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "1939-11-06",
		Language:        "English",
		PageCount:       272,
		CategorySlugs:   []string{"mystery"},
		AuthorCodes:     []string{"agatha-christie"},
	},
	{
		ID:              UUIDFromString("book:9780062073556"),
		ISBN:            "9780062073556",
		Title:           "The ABC Murders",
		Description:     "Poirot races to stop a serial killer working through the alphabet.",
		Price:           12.99,
		Stock:           170,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "1936-01-06",
		Language:        "English",
		PageCount:       288,
		CategorySlugs:   []string{"mystery", "thriller"},
		AuthorCodes:     []string{"agatha-christie"},
	},
	{
		ID:              UUIDFromString("book:9780307588371"),
		ISBN:            "9780307588371",
		Title:           "Gone Girl",
		Description:     "A marriage unravels into a dark, media-fueled mystery.",
		Price:           16.99,
		Stock:           150,
		PublisherCode:   "crown",
		CoverImageURL:   "",
		PublicationDate: "2012-06-05",
		Language:        "English",
		PageCount:       432,
		CategorySlugs:   []string{"thriller"},
		AuthorCodes:     []string{"gillian-flynn"},
	},
	{
		ID:              UUIDFromString("book:9780307341556"),
		ISBN:            "9780307341556",
		Title:           "Sharp Objects",
		Description:     "A journalist investigates brutal murders in her hometown while confronting personal demons.",
		Price:           15.99,
		Stock:           145,
		PublisherCode:   "crown",
		CoverImageURL:   "",
		PublicationDate: "2006-09-26",
		Language:        "English",
		PageCount:       272,
		CategorySlugs:   []string{"thriller", "mystery"},
		AuthorCodes:     []string{"gillian-flynn"},
	},
	{
		ID:              UUIDFromString("book:9781455519002"),
		ISBN:            "9781455519002",
		Title:           "The Innocent",
		Description:     "A government assassin becomes a target after a mission goes wrong.",
		Price:           14.99,
		Stock:           130,
		PublisherCode:   "hachette-book-group",
		CoverImageURL:   "",
		PublicationDate: "2012-04-17",
		Language:        "English",
		PageCount:       432,
		CategorySlugs:   []string{"thriller"},
		AuthorCodes:     []string{"david-baldacci"},
	},
	{
		ID:              UUIDFromString("book:9781455586400"),
		ISBN:            "9781455586400",
		Title:           "Memory Man",
		Description:     "Detective Amos Decker uses his perfect memory to solve a deadly case.",
		Price:           15.99,
		Stock:           128,
		PublisherCode:   "hachette-book-group",
		CoverImageURL:   "",
		PublicationDate: "2015-04-21",
		Language:        "English",
		PageCount:       432,
		CategorySlugs:   []string{"thriller", "mystery"},
		AuthorCodes:     []string{"david-baldacci"},
	},
	{
		ID:              UUIDFromString("book:9781984822178"),
		ISBN:            "9781984822178",
		Title:           "Normal People",
		Description:     "Two Irish teenagers navigate love, class, and identity across years.",
		Price:           17.99,
		Stock:           140,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2019-04-16",
		Language:        "English",
		PageCount:       304,
		CategorySlugs:   []string{"romance", "young-adult"},
		AuthorCodes:     []string{"sally-rooney"},
	},
	{
		ID:              UUIDFromString("book:9780451499059"),
		ISBN:            "9780451499059",
		Title:           "Conversations with Friends",
		Description:     "Complex relationships and creative ambitions collide among Dublin artists.",
		Price:           16.99,
		Stock:           135,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2017-07-11",
		Language:        "English",
		PageCount:       320,
		CategorySlugs:   []string{"romance", "young-adult"},
		AuthorCodes:     []string{"sally-rooney"},
	},
	{
		ID:              UUIDFromString("book:9780307455925"),
		ISBN:            "9780307455925",
		Title:           "Americanah",
		Description:     "A sweeping story of love and identity spanning Nigeria, the UK, and the US.",
		Price:           17.99,
		Stock:           150,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2013-05-14",
		Language:        "English",
		PageCount:       608,
		CategorySlugs:   []string{"romance", "history"},
		AuthorCodes:     []string{"chimamanda-ngozi-adichie"},
	},
	{
		ID:              UUIDFromString("book:9781400095209"),
		ISBN:            "9781400095209",
		Title:           "Half of a Yellow Sun",
		Description:     "Lives are upended during the Biafran War in this epic of family and resilience.",
		Price:           16.99,
		Stock:           142,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2006-09-12",
		Language:        "English",
		PageCount:       560,
		CategorySlugs:   []string{"history", "romance"},
		AuthorCodes:     []string{"chimamanda-ngozi-adichie"},
	},
	{
		ID:              UUIDFromString("book:9780385542364"),
		ISBN:            "9780385542364",
		Title:           "The Underground Railroad",
		Description:     "A reinvention of the Underground Railroad as an actual subterranean network.",
		Price:           17.99,
		Stock:           138,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2016-08-02",
		Language:        "English",
		PageCount:       336,
		CategorySlugs:   []string{"history"},
		AuthorCodes:     []string{"colson-whitehead"},
	},
	{
		ID:              UUIDFromString("book:9780385537070"),
		ISBN:            "9780385537070",
		Title:           "The Nickel Boys",
		Description:     "Two boys endure the brutality of a Jim Crow-era reform school.",
		Price:           16.99,
		Stock:           128,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "https://m.media-amazon.com/images/I/71wTpp0IsUL._SY466_.jpg",
		PublicationDate: "2019-07-16",
		Language:        "English",
		PageCount:       224,
		CategorySlugs:   []string{"history", "biography"},
		AuthorCodes:     []string{"colson-whitehead"},
	},
	{
		ID:              UUIDFromString("book:9781524763138"),
		ISBN:            "9781524763138",
		Title:           "Becoming",
		Description:     "Michelle Obama reflects on her journey from Chicago to the White House.",
		Price:           32.50,
		Stock:           200,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "https://m.media-amazon.com/images/I/81yyfjVd1ML._SY466_.jpg",
		PublicationDate: "2018-11-13",
		Language:        "English",
		PageCount:       448,
		CategorySlugs:   []string{"biography", "self-help"},
		AuthorCodes:     []string{"michelle-obama"},
	},
	{
		ID:              UUIDFromString("book:9781451648539"),
		ISBN:            "9781451648539",
		Title:           "Steve Jobs",
		Description:     "Definitive biography of Apple's visionary cofounder.",
		Price:           20.99,
		Stock:           160,
		PublisherCode:   "simon-schuster",
		CoverImageURL:   "https://m.media-amazon.com/images/I/71sVQDj0SCL._SY466_.jpg",
		PublicationDate: "2011-10-24",
		Language:        "English",
		PageCount:       656,
		CategorySlugs:   []string{"biography", "technology"},
		AuthorCodes:     []string{"walter-isaacson"},
	},
	{
		ID:              UUIDFromString("book:9781501139154"),
		ISBN:            "9781501139154",
		Title:           "Leonardo da Vinci",
		Description:     "A richly detailed portrait of the Renaissance polymath.",
		Price:           22.99,
		Stock:           150,
		PublisherCode:   "simon-schuster",
		CoverImageURL:   "https://m.media-amazon.com/images/I/91WzYOS4niL._SY466_.jpg",
		PublicationDate: "2017-10-17",
		Language:        "English",
		PageCount:       624,
		CategorySlugs:   []string{"biography", "history"},
		AuthorCodes:     []string{"walter-isaacson"},
	},
	{
		ID:              UUIDFromString("book:9780062316097"),
		ISBN:            "9780062316097",
		Title:           "Sapiens",
		Description:     "A sweeping history of humankind from the Stone Age to the modern era.",
		Price:           22.99,
		Stock:           175,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "2015-02-10",
		Language:        "English",
		PageCount:       512,
		CategorySlugs:   []string{"history", "science-nature"},
		AuthorCodes:     []string{"yuval-noah-harari"},
	},
	{
		ID:              UUIDFromString("book:9780525512172"),
		ISBN:            "9780525512172",
		Title:           "21 Lessons for the 21st Century",
		Description:     "Insights on technology, politics, and meaning in the modern world.",
		Price:           18.99,
		Stock:           140,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "https://m.media-amazon.com/images/I/7185tje+87L._SY466_.jpg",
		PublicationDate: "2018-09-04",
		Language:        "English",
		PageCount:       400,
		CategorySlugs:   []string{"history", "philosophy"},
		AuthorCodes:     []string{"yuval-noah-harari"},
	},
	{
		ID:              UUIDFromString("book:9781455586691"),
		ISBN:            "9781455586691",
		Title:           "Deep Work",
		Description:     "Rules for focused success in a distracted world.",
		Price:           17.99,
		Stock:           190,
		PublisherCode:   "hachette-book-group",
		CoverImageURL:   "",
		PublicationDate: "2016-01-05",
		Language:        "English",
		PageCount:       304,
		CategorySlugs:   []string{"self-help", "business"},
		AuthorCodes:     []string{"cal-newport"},
	},
	{
		ID:              UUIDFromString("book:9780525536512"),
		ISBN:            "9780525536512",
		Title:           "Digital Minimalism",
		Description:     "Choosing a focused life in a noisy world.",
		Price:           17.99,
		Stock:           185,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "https://m.media-amazon.com/images/I/81x+9opgESL._SY466_.jpg",
		PublicationDate: "2019-02-05",
		Language:        "English",
		PageCount:       304,
		CategorySlugs:   []string{"self-help", "technology"},
		AuthorCodes:     []string{"cal-newport"},
	},
	{
		ID:              UUIDFromString("book:9780399592522"),
		ISBN:            "9780399592522",
		Title:           "Dare to Lead",
		Description:     "Practical guidance on courageous, compassionate leadership.",
		Price:           28.00,
		Stock:           160,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "https://m.media-amazon.com/images/I/71qXI7x+mUL._SY466_.jpg",
		PublicationDate: "2018-10-09",
		Language:        "English",
		PageCount:       320,
		CategorySlugs:   []string{"self-help", "business"},
		AuthorCodes:     []string{"brene-brown"},
	},
	{
		ID:              UUIDFromString("book:9780399592553"),
		ISBN:            "9780399592553",
		Title:           "Atlas of the Heart",
		Description:     "Mapping the language and experiences of human emotion.",
		Price:           30.00,
		Stock:           140,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2021-11-30",
		Language:        "English",
		PageCount:       336,
		CategorySlugs:   []string{"self-help", "health-wellness"},
		AuthorCodes:     []string{"brene-brown"},
	},
	{
		ID:              UUIDFromString("book:9780857197689"),
		ISBN:            "9780857197689",
		Title:           "The Psychology of Money",
		Description:     "Timeless lessons on wealth, greed, and happiness.",
		Price:           19.99,
		Stock:           210,
		PublisherCode:   "wiley-business",
		CoverImageURL:   "",
		PublicationDate: "2020-09-08",
		Language:        "English",
		PageCount:       256,
		CategorySlugs:   []string{"financial", "business"},
		AuthorCodes:     []string{"morgan-housel"},
	},
	{
		ID:              UUIDFromString("book:9780140280197"),
		ISBN:            "9780140280197",
		Title:           "The 48 Laws of Power",
		Description:     "Strategies drawn from history for navigating power dynamics.",
		Price:           25.00,
		Stock:           170,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2000-09-01",
		Language:        "English",
		PageCount:       496,
		CategorySlugs:   []string{"business", "philosophy"},
		AuthorCodes:     []string{"robert-greene"},
	},
	{
		ID:              UUIDFromString("book:9780143124178"),
		ISBN:            "9780143124178",
		Title:           "Mastery",
		Description:     "Lessons from great masters on how to achieve excellence.",
		Price:           18.00,
		Stock:           165,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2013-10-29",
		Language:        "English",
		PageCount:       352,
		CategorySlugs:   []string{"business", "self-help"},
		AuthorCodes:     []string{"robert-greene"},
	},
	{
		ID:              UUIDFromString("book:9781400052189"),
		ISBN:            "9781400052189",
		Title:           "The Immortal Life of Henrietta Lacks",
		Description:     "The true story behind the HeLa cells that transformed medical research.",
		Price:           17.00,
		Stock:           150,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "https://m.media-amazon.com/images/I/81coyP8S-ZL._SY522_.jpg",
		PublicationDate: "2010-02-02",
		Language:        "English",
		PageCount:       400,
		CategorySlugs:   []string{"science-nature", "biography"},
		AuthorCodes:     []string{"rebecca-skloot"},
	},
	{
		ID:              UUIDFromString("book:9781582346816"),
		ISBN:            "9781582346816",
		Title:           "Kitchen Confidential",
		Description:     "Behind-the-scenes look at professional kitchens with grit and humor.",
		Price:           16.99,
		Stock:           155,
		PublisherCode:   "bloomsbury",
		CoverImageURL:   "",
		PublicationDate: "2000-05-22",
		Language:        "English",
		PageCount:       320,
		CategorySlugs:   []string{"cooking", "travel-adventure"},
		AuthorCodes:     []string{"anthony-bourdain"},
	},
	{
		ID:              UUIDFromString("book:9780062802798"),
		ISBN:            "9780062802798",
		Title:           "World Travel",
		Description:     "Entertaining guide to Anthony Bourdain's favorite places and dishes.",
		Price:           35.00,
		Stock:           100,
		PublisherCode:   "harpercollins",
		CoverImageURL:   "",
		PublicationDate: "2021-04-20",
		Language:        "English",
		PageCount:       480,
		CategorySlugs:   []string{"travel-adventure", "cooking"},
		AuthorCodes:     []string{"anthony-bourdain"},
	},
	{
		ID:              UUIDFromString("book:9780307279460"),
		ISBN:            "9780307279460",
		Title:           "A Walk in the Woods",
		Description:     "A humorous trek along the Appalachian Trail with insights on conservation.",
		Price:           16.00,
		Stock:           142,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "1998-05-04",
		Language:        "English",
		PageCount:       400,
		CategorySlugs:   []string{"travel-adventure", "health-wellness"},
		AuthorCodes:     []string{"bill-bryson"},
	},
	{
		ID:              UUIDFromString("book:9780767908187"),
		ISBN:            "9780767908187",
		Title:           "A Short History of Nearly Everything",
		Description:     "A tour through scientific discoveries that explain our world.",
		Price:           18.00,
		Stock:           150,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "https://m.media-amazon.com/images/I/81omBfA9GvL._SY466_.jpg",
		PublicationDate: "2003-05-06",
		Language:        "English",
		PageCount:       544,
		CategorySlugs:   []string{"science-nature", "technology"},
		AuthorCodes:     []string{"bill-bryson"},
	},
	{
		ID:              UUIDFromString("book:9780393348745"),
		ISBN:            "9780393348745",
		Title:           "Gulp",
		Description:     "A witty exploration of the human digestive system.",
		Price:           15.95,
		Stock:           132,
		PublisherCode:   "ww-norton",
		CoverImageURL:   "",
		PublicationDate: "2014-04-01",
		Language:        "English",
		PageCount:       352,
		CategorySlugs:   []string{"science-nature", "health-wellness"},
		AuthorCodes:     []string{"mary-roach"},
	},
	{
		ID:              UUIDFromString("book:9780393324824"),
		ISBN:            "9780393324824",
		Title:           "Stiff",
		Description:     "An offbeat look at the curious lives of human cadavers.",
		Price:           15.95,
		Stock:           128,
		PublisherCode:   "ww-norton",
		CoverImageURL:   "",
		PublicationDate: "2004-04-17",
		Language:        "English",
		PageCount:       320,
		CategorySlugs:   []string{"science-nature", "philosophy"},
		AuthorCodes:     []string{"mary-roach"},
	},
	{
		ID:              UUIDFromString("book:9780393609396"),
		ISBN:            "9780393609396",
		Title:           "Astrophysics for People in a Hurry",
		Description:     "An accessible overview of the cosmos by a renowned astrophysicist.",
		Price:           18.95,
		Stock:           170,
		PublisherCode:   "ww-norton",
		CoverImageURL:   "https://m.media-amazon.com/images/I/914EiU2QImL._SY522_.jpg",
		PublicationDate: "2017-05-02",
		Language:        "English",
		PageCount:       224,
		CategorySlugs:   []string{"science-nature", "technology"},
		AuthorCodes:     []string{"neil-degrasse-tyson"},
	},
	{
		ID:              UUIDFromString("book:9781426221774"),
		ISBN:            "9781426221774",
		Title:           "Cosmic Queries",
		Description:     "Answers to humanity's biggest questions about the universe.",
		Price:           30.00,
		Stock:           120,
		PublisherCode:   "national-geographic",
		CoverImageURL:   "https://m.media-amazon.com/images/I/810Tu2XgSBL._SY466_.jpg",
		PublicationDate: "2021-03-02",
		Language:        "English",
		PageCount:       312,
		CategorySlugs:   []string{"science-nature", "technology"},
		AuthorCodes:     []string{"neil-degrasse-tyson"},
	},
	{
		ID:              UUIDFromString("book:9781400079278"),
		ISBN:            "9781400079278",
		Title:           "Kafka on the Shore",
		Description:     "Two narratives intertwine in a surreal exploration of memory and destiny.",
		Price:           17.00,
		Stock:           125,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2005-01-18",
		Language:        "English",
		PageCount:       480,
		CategorySlugs:   []string{"fantasy", "philosophy"},
		AuthorCodes:     []string{"haruki-murakami"},
	},
	{
		ID:              UUIDFromString("book:9780307476463"),
		ISBN:            "9780307476463",
		Title:           "1Q84",
		Description:     "A sprawling, dreamlike tale of parallel realities and mysterious cults.",
		Price:           19.95,
		Stock:           118,
		PublisherCode:   "penguin-random-house",
		CoverImageURL:   "",
		PublicationDate: "2011-10-25",
		Language:        "English",
		PageCount:       944,
		CategorySlugs:   []string{"fantasy", "mystery"},
		AuthorCodes:     []string{"haruki-murakami"},
	},
}

// GetBooks returns a copy of the configured book seeds.
func GetBooks() []BookSeed {
	result := make([]BookSeed, len(bookSeeds))
	copy(result, bookSeeds)
	return result
}
