apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: bookstore-dev
data:
  APP_NAME: "Inventory Service"
  APP_VERSION: "1.0.0"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  LOW_STOCK_THRESHOLD: "10"
  RESERVATION_EXPIRY_MINUTES: "15"
