apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: bookstore-dev
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: 905418472239.dkr.ecr.us-east-1.amazonaws.com/review-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8088
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: review-service-secrets
              key: DATABASE_URL
        envFrom:
        - configMapRef:
            name: review-service-config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
