apiVersion: v1
kind: Secret
metadata:
  name: review-service-secrets
  namespace: bookstore-dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://bookstore:dev_password@postgres:5432/reviews_db"
