apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secrets
  namespace: bookstore-dev
type: Opaque
stringData:
  database-url: "postgresql://bookstore:dev_password@postgres:5432/bookstore?sslmode=disable"
  jwt-secret: "your-super-secret-jwt-key-change-in-production-min-32-chars"
